language: node_js

node_js:
  - "6"
  - "7"

cache:
  directories:
    - "node_modules"

before_deploy:
  - npm run build

deploy:
  provider: surge
  project: ./target/
  domain: pwa-investigation.surge.sh